---
- hosts: dotest3
  remote_user: root
  sudo: yes
  gather_facts: no

  roles:
    - common
    - users
    - ssh
    - erlang
    - rbenv
    - postgres
    - elixir
    - nginx
    - watchsumo-gui
